=== fr830/softplc/softplc/src/test/resources/softplc.dtd
<!ELEMENT softplc (includes | cpu)*>

<!ELEMENT includes EMPTY>
<!ATTLIST includes
	file	CDATA	#REQUIRED
>

<!ELEMENT cpu (memory, program)*>
<!ATTLIST cpu
	slot		CDATA		#REQUIRED
	connections	CDATA		"32"
	maxBlockSize	CDATA	"222"
>

<!ELEMENT memory (area)*>

<!ELEMENT area EMPTY>
<!ATTLIST area
	name	CDATA	#REQUIRED
	size	CDATA	"65535"
>

<!ELEMENT program (file)*>
<!ATTLIST program
	cycleTime	CDATA	"20"
>

<!ELEMENT file (#PCDATA)>

=== fr830/softplc/softplc/src/test/resources/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE softplc SYSTEM "softplc.dtd">
<softplc>
	<cpu slot="1" connections="64">
		<memory>
			<area name="DB100" size="2000" />
			<area name="DB101" size="1000" />
		</memory>

		<program cycleTime="50" file="./src/test/resources/program/main.js" />
	</cpu>

	<cpu slot="2">
		<memory>
			<area name="M" size="8000"/>
			<area name="DB100" size="2000" />
			<area name="DB101" size="1000" />
		</memory>

		<program cycleTime="50" file="./src/test/resources/program/main.js" />
	</cpu>
</softplc>
